# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

let
  btrfs-options = "rw,noatime,compress=zstd:3,ssd,discard=async,space_cache=v2,commit=120";
in
{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/1b3938f0-358f-4358-b7fb-b448b6eba56a";
      fsType = "btrfs";
      options = [ "${btrfs-options},subvol=@nixos" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/1b3938f0-358f-4358-b7fb-b448b6eba56a";
      fsType = "btrfs";
      options = [ "${btrfs-options},subvol=@nix" ];
    };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/1861-1CA6";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/1b3938f0-358f-4358-b7fb-b448b6eba56a";
      fsType = "btrfs";
      options = [ "${btrfs-options},subvol=@home" ];
    };

  fileSystems."/var/lib/docker" = 
    { device = "/dev/disk/by-uuid/1b3938f0-358f-4358-b7fb-b448b6eba56a";
      fsType = "btrfs";
      options = [ "${btrfs-options},subvol=@docker" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
